export const scheduleConstants = {
    SCHEDULE_CONSTRAINT_LOAD: 'SCHEDULE_CONSTRAINT_LOAD',
    SCHEDULE_CONSTRAINT_UPDATE: 'SCHEDULE_CONSTRAINT_UPDATE',
    SCHEDULE_DEMAND_LOAD: 'SCHEDULE_DEMAND_LOAD',
    SCHEDULE_DEMAND_UPDATE: 'SCHEDULE_DEMAND_UPDATE',

    SCHEDULE_DATA_INPUT: 'SCHEDULE_DATA_INPUT',

    FETCH_WEEK_SCHEDULES: "FETCH_WEEK_SCHEDULES",
    FETCH_WEEK_SCHEDULE: "FETCH_WEEK_SCHEDULE",
    FETCH_SKILL_SRC: "FETCH_SKILL_SRC"
};